In [3]:
pip install meteostat

Collecting meteostat
  Downloading meteostat-2.1.4-py3-none-any.whl.metadata (5.2 kB)
Collecting pandas<4.0.0,>=2.3.0 (from meteostat)
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 5.4 MB/s eta 0:00:00
Collecting pytz<2024.0,>=2023.3.post1 (from meteostat)
  Downloading pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from meteostat) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=2.3.0->meteostat) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=2.3.0->meteostat) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->meteostat) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->meteostat) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->meteostat) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->meteostat) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0.0,>=2.3.0->meteostat) (1.17.0)
Downloading meteostat-2.1.4-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.8/93.8 kB 7.1 MB/s eta 0:00:00
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 98.1 MB/s eta 0:00:00
Downloading pytz-2023.4-py2.py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.5/506.5 kB 26.3 MB/s eta 0:00:00
Installing collected packages: pytz, pandas, meteostat
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.2 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.2 which is incompatible.
Successfully installed meteostat-2.1.4 pandas-3.0.2 pytz-2023.4

In [4]:
import meteostat
print(meteostat.__version__)

2.1.4

In [5]:
from datetime import date
import meteostat as ms

point = ms.Point(49.39, 20.87)
start = date(2019, 6, 1)
end = date(2025, 9, 30)

stations = ms.stations.nearby(point, limit=10)
print(stations)

ts = ms.daily(stations, start, end)
df = ms.interpolate(ts, point).fetch()

print(df.shape)
print(df.head())

            name country region  latitude  longitude  elevation  \
id
12660  Nowy Sacz      PL     ML   49.6167       20.7        292

            timezone  distance
id
12660  Europe/Warsaw   28038.0
(2314, 9)
            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2019-06-01  15.9   8.5  22.8    79  <NA>   4.6  18.5  1021.9  <NA>
2019-06-02  18.9  12.5  25.2    72  <NA>   4.7  18.5  1019.5  <NA>
2019-06-03  19.6  11.4  26.4    67  <NA>   6.3  24.1  1017.9  <NA>
2019-06-04  20.2  13.1  26.6    69  <NA>   6.4  25.9  1014.2  <NA>
2019-06-05  20.1  13.7  26.5    69  <NA>   7.5  25.9  1011.6  <NA>

In [6]:
df_jul_sep = df[df.index.month.isin([6, 7, 8, 9])]

df_jul_sep.head()

            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2019-06-01  15.9   8.5  22.8    79  <NA>   4.6  18.5  1021.9  <NA>
2019-06-02  18.9  12.5  25.2    72  <NA>   4.7  18.5  1019.5  <NA>
2019-06-03  19.6  11.4  26.4    67  <NA>   6.3  24.1  1017.9  <NA>
2019-06-04  20.2  13.1  26.6    69  <NA>   6.4  25.9  1014.2  <NA>
2019-06-05  20.1  13.7  26.5    69  <NA>   7.5  25.9  1011.6  <NA>

In [7]:
df_jul_sep.tail()

            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2025-09-26  10.9   8.0  14.6    82   0.5   5.7  22.2  1027.8     7
2025-09-27  11.2   4.9  18.2    75   0.0   3.8  16.7  1026.4     3
2025-09-28   9.1   5.0  13.6    81   0.0   4.1  16.7  1023.1     5
2025-09-29   8.5   6.8   9.6    88   5.7   5.0  18.5  1022.6     8
2025-09-30   7.8   7.1   8.8    94   5.1   4.7  14.8  1025.1     8

In [8]:
df_jul_sep['year'] = df_jul_sep.index.year
df_jul_sep['month'] = df_jul_sep.index.month

In [9]:
df_jul_sep.head()

,temp,tmin,tmax,rhum,prcp,wspd,wpgt,pres,cldc,year,month
time,,,,,,,,,,,
2019-06-01,15.9,8.5,22.8,79,<NA>,4.6,18.5,1021.9,<NA>,2019,6
2019-06-02,18.9,12.5,25.2,72,<NA>,4.7,18.5,1019.5,<NA>,2019,6
2019-06-03,19.6,11.4,26.4,67,<NA>,6.3,24.1,1017.9,<NA>,2019,6
2019-06-04,20.2,13.1,26.6,69,<NA>,6.4,25.9,1014.2,<NA>,2019,6
2019-06-05,20.1,13.7,26.5,69,<NA>,7.5,25.9,1011.6,<NA>,2019,6

In [10]:
groups = df_jul_sep.groupby(df_jul_sep.index.year)

for year, group in groups:
    print(year, group.shape)

2019 (122, 11)
2020 (122, 11)
2021 (122, 11)
2022 (122, 11)
2023 (122, 11)
2024 (122, 11)
2025 (122, 11)

In [11]:
df_jul_sep["day"] = df_jul_sep.index.day
df_jul_sep["week"] = df_jul_sep.index.isocalendar().week

In [12]:
df_jul_sep.head(20)

,temp,tmin,tmax,rhum,prcp,wspd,wpgt,pres,cldc,year,month,day,week
time,,,,,,,,,,,,,
2019-06-01,15.9,8.5,22.8,79,<NA>,4.6,18.5,1021.9,<NA>,2019,6,1,22
2019-06-02,18.9,12.5,25.2,72,<NA>,4.7,18.5,1019.5,<NA>,2019,6,2,22
2019-06-03,19.6,11.4,26.4,67,<NA>,6.3,24.1,1017.9,<NA>,2019,6,3,23
2019-06-04,20.2,13.1,26.6,69,<NA>,6.4,25.9,1014.2,<NA>,2019,6,4,23
2019-06-05,20.1,13.7,26.5,69,<NA>,7.5,25.9,1011.6,<NA>,2019,6,5,23
2019-06-06,19.8,13.1,24.6,64,<NA>,7.4,27.8,1012.3,<NA>,2019,6,6,23
2019-06-07,20.4,14.9,25.8,72,<NA>,4.8,16.7,1014.8,<NA>,2019,6,7,23
2019-06-08,21.6,14.7,28.7,69,<NA>,5.3,20.4,1018.1,<NA>,2019,6,8,23
2019-06-09,20.9,17.2,25.1,62,<NA>,6.8,20.4,1024.8,<NA>,2019,6,9,23
2019-06-10,23.3,14.3,31.1,64,<NA>,6.8,25.9,1017.7,<NA>,2019,6,10,24
2019-06-11,25.0,16.2,31.5,56,<NA>,8.4,35.2,1014.0,<NA>,2019,6,11,24
2019-06-12,25.3,17.1,31.8,53,<NA>,8.0,33.3,1013.2,<NA>,2019,6,12,24
2019-06-13,26.2,17.5,33.3,55,<NA>,5.9,24.1,1013.2,<NA>,2019,6,13,24
2019-06-14,25.1,19.6,29.9,68,<NA>,5.5,16.7,1017.2,<NA>,2019,6,14,24
2019-06-15,25.9,18.3,33.9,65,<NA>,4.8,22.2,1014.2,<NA>,2019,6,15,24
2019-06-16,22.8,19.0,29.3,74,<NA>,5.6,20.4,1015.0,<NA>,2019,6,16,24
2019-06-17,17.9,13.7,20.6,79,<NA>,4.1,16.7,1020.9,<NA>,2019,6,17,25
2019-06-18,17.6,10.9,23.2,78,<NA>,5.4,22.2,1019.4,<NA>,2019,6,18,25
2019-06-19,20.6,14.9,28.7,79,<NA>,5.1,16.7,1014.1,<NA>,2019,6,19,25
2019-06-20,20.3,16.5,26.2,83,<NA>,5.6,14.8,1012.1,<NA>,2019,6,20,25

In [13]:
col = ['temp', 'tmin', 'tmax', 'rhum', 'wspd', 'wpgt', 'pres']

mean_week = df_jul_sep.groupby(["year", "week"])[col].mean()

In [14]:
mean_week

                temp       tmin       tmax       rhum      wspd       wpgt  \
year week
2019 22         17.4       10.5       24.0       75.5      4.65       18.5
     23    20.371429  14.014286  26.242857  67.428571  6.357143  23.028571
     24         24.8  17.428571  31.542857  62.142857  6.428571       25.4
     25    19.571429  15.171429  24.957143  80.428571       5.1       17.2
     26    22.528571       16.0  28.285714  61.714286  6.685714  25.414286
...              ...        ...        ...        ...       ...        ...
2025 36    19.342857       15.3       24.2  81.714286  4.385714  19.328571
     37         17.4  13.371429  21.828571  82.714286  4.628571  19.314286
     38    16.628571  11.228571  21.885714  75.428571  5.785714  23.042857
     39    12.314286   8.971429       16.3  79.714286  5.871429       21.7
     40         8.15       6.95        9.2       91.0      4.85      16.65

                  pres
year week
2019 22         1020.7
     23    1016.242857
     24    1014.928571
     25    1017.085714
     26    1020.728571
...                ...
2025 36    1016.642857
     37         1016.5
     38    1020.914286
     39         1023.1
     40        1023.85

[129 rows x 7 columns]

In [15]:
mean_week.to_csv("meen_week.csv")

In [16]:
mean_week.describe()

,temp,tmin,tmax,rhum,wspd,wpgt,pres
count,129.0,129.0,129.0,129.0,129.0,128.0,129.0
mean,18.14493,12.890203,23.872062,74.273902,5.25672,20.728242,1016.139304
std,3.198789,2.875468,3.930182,7.495525,1.49471,5.139398,4.272534
min,8.1,3.5,9.2,53.428571,3.457143,14.3,1003.4
25%,16.242857,10.985714,21.828571,69.857143,4.485714,17.6,1013.257143
50%,18.4,13.242857,24.185714,75.142857,4.914286,19.842857,1016.157143
75%,20.5,15.1,26.714286,79.142857,5.6,22.653571,1018.78
max,24.8,18.6,31.542857,91.0,18.3,61.1,1024.828571