In [1]:
import meteostat
print(meteostat.__version__)

2.1.4

In [18]:
from datetime import date
import meteostat as ms

point = ms.Point(49.39, 20.87)
start = date(2019, 7, 1)
end = date(2025, 9, 30)

stations = ms.stations.nearby(point, limit=10)
print(stations)

ts = ms.daily(stations, start, end)
df = ms.interpolate(ts, point).fetch()

print(df.shape)
print(df.head())

            name country region  latitude  longitude  elevation  \
id
12660  Nowy Sacz      PL     ML   49.6167       20.7        292

            timezone  distance
id
12660  Europe/Warsaw   28038.0
(2284, 9)
            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2019-07-01  27.0  18.6  35.8    49  <NA>   7.4  22.2  1013.1  <NA>
2019-07-02  23.3  19.1  26.2    54  <NA>   6.8  24.1  1014.9  <NA>
2019-07-03  18.1  12.0  23.0    52  <NA>   6.8  25.9  1019.1  <NA>
2019-07-04  16.5   7.9  23.4    53  <NA>   5.0  20.4  1020.9  <NA>
2019-07-05  17.3   8.6  23.5    58  <NA>   5.4  24.1  1014.9  <NA>

In [3]:
df_jul_sep = df[df.index.month.isin([7, 8, 9])]

df_jul_sep.head()

            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2019-07-01  27.0  18.6  35.8    49  <NA>   7.4  22.2  1013.1  <NA>
2019-07-02  23.3  19.1  26.2    54  <NA>   6.8  24.1  1014.9  <NA>
2019-07-03  18.1  12.0  23.0    52  <NA>   6.8  25.9  1019.1  <NA>
2019-07-04  16.5   7.9  23.4    53  <NA>   5.0  20.4  1020.9  <NA>
2019-07-05  17.3   8.6  23.5    58  <NA>   5.4  24.1  1014.9  <NA>

In [4]:
df_jul_sep.tail()

            temp  tmin  tmax  rhum  prcp  wspd  wpgt    pres  cldc
time
2025-09-26  10.9   8.0  14.6    82   0.5   5.7  22.2  1027.8     7
2025-09-27  11.2   4.9  18.2    75   0.0   3.8  16.7  1026.4     3
2025-09-28   9.1   5.0  13.6    81   0.0   4.1  16.7  1023.1     5
2025-09-29   8.5   6.8   9.6    88   5.7   5.0  18.5  1022.6     8
2025-09-30   7.8   7.1   8.8    94   5.1   4.7  14.8  1025.1     8

In [5]:
df_jul_sep['year'] = df_jul_sep.index.year
df_jul_sep['month'] = df_jul_sep.index.month

In [6]:
df_jul_sep.head()

,temp,tmin,tmax,rhum,prcp,wspd,wpgt,pres,cldc,year,month
time,,,,,,,,,,,
2019-07-01,27.0,18.6,35.8,49,<NA>,7.4,22.2,1013.1,<NA>,2019,7
2019-07-02,23.3,19.1,26.2,54,<NA>,6.8,24.1,1014.9,<NA>,2019,7
2019-07-03,18.1,12.0,23.0,52,<NA>,6.8,25.9,1019.1,<NA>,2019,7
2019-07-04,16.5,7.9,23.4,53,<NA>,5.0,20.4,1020.9,<NA>,2019,7
2019-07-05,17.3,8.6,23.5,58,<NA>,5.4,24.1,1014.9,<NA>,2019,7

In [7]:
groups = df_jul_sep.groupby(df_jul_sep.index.year)

for year, group in groups:
    print(year, group.shape)

2019 (92, 11)
2020 (92, 11)
2021 (92, 11)
2022 (92, 11)
2023 (92, 11)
2024 (92, 11)
2025 (92, 11)

In [10]:
df_jul_sep["day"] = df_jul_sep.index.day
df_jul_sep["week"] = df_jul_sep.index.isocalendar().week

In [12]:
df_jul_sep.head(20)

,temp,tmin,tmax,rhum,prcp,wspd,wpgt,pres,cldc,year,month,day,week
time,,,,,,,,,,,,,
2019-07-01,27.0,18.6,35.8,49,<NA>,7.4,22.2,1013.1,<NA>,2019,7,1,27
2019-07-02,23.3,19.1,26.2,54,<NA>,6.8,24.1,1014.9,<NA>,2019,7,2,27
2019-07-03,18.1,12.0,23.0,52,<NA>,6.8,25.9,1019.1,<NA>,2019,7,3,27
2019-07-04,16.5,7.9,23.4,53,<NA>,5.0,20.4,1020.9,<NA>,2019,7,4,27
2019-07-05,17.3,8.6,23.5,58,<NA>,5.4,24.1,1014.9,<NA>,2019,7,5,27
2019-07-06,21.6,15.4,28.5,48,<NA>,6.8,22.2,1010.4,<NA>,2019,7,6,27
2019-07-07,19.8,15.2,25.9,60,<NA>,6.5,24.1,1006.5,<NA>,2019,7,7,27
2019-07-08,16.4,13.4,20.5,46,<NA>,12.0,38.9,1013.1,<NA>,2019,7,8,28
2019-07-09,15.1,7.7,20.0,50,<NA>,8.9,35.2,1014.5,<NA>,2019,7,9,28
2019-07-10,15.3,12.2,19.5,55,<NA>,10.9,42.6,1014.0,<NA>,2019,7,10,28
2019-07-11,14.2,10.1,18.3,70,<NA>,7.8,29.6,1013.0,<NA>,2019,7,11,28
2019-07-12,16.2,6.3,23.9,59,<NA>,3.8,13.0,1012.1,<NA>,2019,7,12,28
2019-07-13,16.8,13.8,22.1,70,<NA>,4.7,13.0,1010.0,<NA>,2019,7,13,28
2019-07-14,15.8,12.4,20.2,80,<NA>,4.6,16.7,1011.9,<NA>,2019,7,14,28
2019-07-15,16.0,8.6,23.3,62,<NA>,4.7,18.5,1013.6,<NA>,2019,7,15,29
2019-07-16,16.0,8.2,22.7,64,<NA>,5.7,20.4,1013.1,<NA>,2019,7,16,29
2019-07-17,16.8,11.7,20.8,59,<NA>,9.3,38.9,1012.6,<NA>,2019,7,17,29
2019-07-18,17.5,9.9,23.6,60,<NA>,3.5,14.8,1013.8,<NA>,2019,7,18,29
2019-07-19,18.9,9.6,27.7,62,<NA>,5.2,14.8,1015.7,<NA>,2019,7,19,29
2019-07-20,20.4,15.8,26.4,69,<NA>,4.7,18.5,1017.4,<NA>,2019,7,20,29

In [14]:
col = ['temp', 'tmin', 'tmax', 'rhum', 'wspd', 'wpgt', 'pres']

mean_week = df_jul_sep.groupby(["year", "week"])[col].mean()

In [15]:
mean_week

                temp       tmin       tmax       rhum      wspd       wpgt  \
year week
2019 27    20.514286  13.828571  26.614286  53.428571  6.385714  23.285714
     28    15.685714  10.842857  20.642857  61.428571  7.528571       27.0
     29    17.942857  11.414286  24.914286  65.142857  5.542857  20.628571
     30    20.614286       15.5  25.742857  72.571429  4.685714  19.057143
     31         20.5  16.257143  26.014286  70.857143  5.485714  21.157143
...              ...        ...        ...        ...       ...        ...
2025 36    19.342857       15.3       24.2  81.714286  4.385714  19.328571
     37         17.4  13.371429  21.828571  82.714286  4.628571  19.314286
     38    16.628571  11.228571  21.885714  75.428571  5.785714  23.042857
     39    12.314286   8.971429       16.3  79.714286  5.871429       21.7
     40         8.15       6.95        9.2       91.0      4.85      16.65

                  pres
year week
2019 27    1014.257143
     28    1012.657143
     29    1014.971429
     30    1014.657143
     31    1011.157143
...                ...
2025 36    1016.642857
     37         1016.5
     38    1020.914286
     39         1023.1
     40        1023.85

[98 rows x 7 columns]

In [17]:
mean_week.to_csv("meen_week.csv")

In [19]:
mean_week.describe()

,temp,tmin,tmax,rhum,wspd,wpgt,pres
count,98.0,98.0,98.0,98.0,98.0,98.0,98.0
mean,17.960124,12.88749,23.628989,75.352672,5.135972,20.344597,1016.080326
std,3.366289,2.965589,4.181242,7.129808,1.617329,5.407169,4.553531
min,8.1,3.5,9.2,53.428571,3.457143,14.3,1003.4
25%,16.101786,11.046429,21.729464,72.178571,4.446429,17.485714,1013.075
50%,18.271429,13.235714,23.928571,75.928571,4.8,19.571429,1015.992857
75%,20.535714,15.2125,26.667857,79.714286,5.464286,21.7,1019.101786
max,23.271429,18.6,30.2,91.0,18.3,61.1,1024.828571